filebeat.prospectors:
- input_type: log
  paths:
    - /host/var/log/*
  json.keys_under_root: true
  processors:
    - decode_json_fields:
         fields: ["message"]
  document_type: HistoryServer
output.logstash:
  hosts: ["10.0.0.1:5044"]
